name: Pylint and Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  pylint_and_tests:
    name: Pylint Check and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pylint
          pip install pytest

      - name: Run Pylint
        run: pylint battleboat.py

      - name: Run Unit Tests
        run: pytest
